import { makeStyles } from '@material-ui/core/styles';
 
export default makeStyles(() => ({
  root: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    padding: '0',
    fontFamily: 'var(--ba-font-body)',
  },
 
  /* ── Hero ──────────────────────────────────────────────── */
  hero: {
    borderRadius: '18px',
    padding: '32px 36px',
    position: 'relative',
    overflow: 'hidden',
    background: 'linear-gradient(135deg, #0B5D1E 0%, #0a2e14 50%, #051008 100%)',
    border: '1px solid rgba(125,255,155,0.15)',
    flexShrink: 0,
    '&::before': {
      content: '""',
      position: 'absolute',
      top: '-40px',
      right: '-40px',
      width: '280px',
      height: '280px',
      background: 'radial-gradient(circle, rgba(125,255,155,0.12) 0%, transparent 60%)',
      pointerEvents: 'none',
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: '1px',
      background: 'linear-gradient(90deg, transparent, rgba(125,255,155,0.3), transparent)',
    },
  },
  heroGrid: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundImage: `
      linear-gradient(rgba(125,255,155,0.03) 1px, transparent 1px),
      linear-gradient(90deg, rgba(125,255,155,0.03) 1px, transparent 1px)
    `,
    backgroundSize: '40px 40px',
    pointerEvents: 'none',
  },
  heroContent: {
    position: 'relative',
    zIndex: 1,
    maxWidth: '55%',
  },
  heroEyebrow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(125,255,155,0.1)',
    border: '1px solid rgba(125,255,155,0.2)',
    borderRadius: '20px',
    padding: '4px 12px',
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--ba-accent)',
    marginBottom: '14px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontFamily: 'var(--ba-font-display)',
    fontSize: '26px',
    fontWeight: 800,
    color: 'var(--ba-text)',
    marginBottom: '8px',
    lineHeight: 1.2,
    '& span': { color: 'var(--ba-accent)' },
  },
  heroSub: {
    fontSize: '13.5px',
    color: 'var(--ba-text2)',
    lineHeight: 1.6,
    marginBottom: '22px',
  },
  heroBtns: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap',
  },
  btnPrimary: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    background: 'linear-gradient(135deg, #1F8A3D, #7DFF9B)',
    color: '#050f08',
    border: 'none',
    borderRadius: '10px',
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'var(--ba-font-body)',
    transition: 'all 0.2s',
    letterSpacing: '0.02em',
    '&:hover': {
      transform: 'translateY(-1px)',
      boxShadow: '0 6px 20px rgba(125,255,155,0.25)',
    },
  },
  btnGhost: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    background: 'rgba(255,255,255,0.06)',
    color: 'var(--ba-text)',
    border: '1px solid rgba(255,255,255,0.12)',
    borderRadius: '10px',
    padding: '10px 20px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'var(--ba-font-body)',
    transition: 'all 0.2s',
    '&:hover': {
      background: 'rgba(255,255,255,0.1)',
      borderColor: 'rgba(125,255,155,0.3)',
    },
  },
  heroStats: {
    position: 'absolute',
    right: '36px',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    zIndex: 1,
    textAlign: 'right',
  },
  heroStatVal: {
    fontFamily: 'var(--ba-font-display)',
    fontSize: '24px',
    fontWeight: 800,
    color: 'var(--ba-accent)',
    lineHeight: 1,
  },
  heroStatLbl: {
    fontSize: '11px',
    color: 'var(--ba-text3)',
    marginTop: '2px',
  },
 
  /* ── Stats grid ────────────────────────────────────────── */
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '16px',
  },
  statCard: {
    background: 'var(--ba-card)',
    border: '1px solid var(--ba-card-border)',
    borderRadius: '16px',
    padding: '18px 20px',
    position: 'relative',
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'all 0.25s',
    '&:hover': {
      transform: 'translateY(-2px)',
      borderColor: 'rgba(125,255,155,0.25)',
      boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
    },
  },
  statTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: '14px',
  },
  statIcon: {
    width: '40px',
    height: '40px',
    borderRadius: '11px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    flexShrink: 0,
  },
  statBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '3px',
    fontSize: '11px',
    fontWeight: 600,
    padding: '3px 8px',
    borderRadius: '20px',
  },
  statVal: {
    fontFamily: 'var(--ba-font-display)',
    fontSize: '26px',
    fontWeight: 800,
    color: 'var(--ba-text)',
    lineHeight: 1,
    marginBottom: '4px',
  },
  statLbl: {
    fontSize: '12px',
    color: 'var(--ba-text3)',
    fontWeight: 400,
  },
  miniBars: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '3px',
    height: '28px',
    marginTop: '12px',
  },
 
  /* ── Charts row ────────────────────────────────────────── */
  chartsRow: {
    display: 'grid',
    gridTemplateColumns: '1.6fr 1fr',
    gap: '16px',
    alignItems: 'stretch',
  },
  chartCard: {
    background: 'var(--ba-card)',
    border: '1px solid var(--ba-card-border)',
    borderRadius: '18px',
    padding: '24px',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.3)',
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 0, left: 0, right: 0,
      height: '1px',
      background: 'linear-gradient(90deg, transparent, rgba(125,255,155,0.2), transparent)',
    },
  },
  chartHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: '16px',
  },
  chartTitle: {
    fontFamily: 'var(--ba-font-display)',
    fontSize: '14px',
    fontWeight: 700,
    color: 'var(--ba-text)',
    marginBottom: '2px',
  },
  chartSub: {
    fontSize: '11px',
    color: 'var(--ba-text3)',
  },
  chartLegend: {
    display: 'flex',
    gap: '14px',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '11px',
    color: 'var(--ba-text2)',
  },
  legendDot: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  chartArea: {
    height: '200px',
    position: 'relative',
  },

  tableCard: {
    background: 'var(--ba-card)',
    border: '1px solid var(--ba-card-border)',
    borderRadius: '18px',
    padding: '24px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.3)',
  },
  activityCard: {
    background: 'var(--ba-card)',
    border: '1px solid var(--ba-card-border)',
    borderRadius: '18px',
    padding: '24px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.3)',
    display: 'flex',
    flexDirection: 'column',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16px',
  },
  sectionTitle: {
    fontFamily: 'var(--ba-font-display)',
    fontSize: '14px',
    fontWeight: 700,
    color: 'var(--ba-text)',
  },
  seeAll: {
    fontSize: '12px',
    color: 'var(--ba-accent)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    opacity: 0.8,
    '&:hover': { opacity: 1 },
  },
 
  /* ── Table ─────────────────────────────────────────────── */
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  th: {
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    color: 'var(--ba-text3)',
    fontWeight: 600,
    textAlign: 'left',
    padding: '0 0 10px',
    borderBottom: '1px solid var(--ba-card-border)',
  },
  td: {
    fontSize: '12.5px',
    color: 'var(--ba-text2)',
    padding: '10px 0',
    borderBottom: '1px solid rgba(125,255,155,0.05)',
    verticalAlign: 'middle',
  },
 
  /* ── Seller avatar ─────────────────────────────────────── */
  sellerAv: {
    width: '26px',
    height: '26px',
    borderRadius: '7px',
    background: 'linear-gradient(135deg, #1F8A3D, #7DFF9B)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    fontWeight: 700,
    color: '#050f08',
    marginRight: '8px',
    verticalAlign: 'middle',
    flexShrink: 0,
  },
 
  /* ── Status pills ──────────────────────────────────────── */
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '3px 10px',
    borderRadius: '20px',
    fontSize: '10px',
    fontWeight: 600,
    letterSpacing: '0.04em',
  },
  pillApproved: {
    background: 'rgba(74,222,128,0.1)',
    color: '#4ade80',
    border: '1px solid rgba(74,222,128,0.2)',
  },
  pillPending: {
    background: 'rgba(251,191,36,0.1)',
    color: '#fbbf24',
    border: '1px solid rgba(251,191,36,0.2)',
  },
  pillRejected: {
    background: 'rgba(248,113,113,0.1)',
    color: '#f87171',
    border: '1px solid rgba(248,113,113,0.2)',
  },
 
  /* ── Activity feed ─────────────────────────────────────── */
  activityList: {
    display: 'flex',
    flexDirection: 'column',
  },
  activityItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    padding: '10px 0',
    borderBottom: '1px solid rgba(125,255,155,0.05)',
    '&:last-child': { borderBottom: 'none' },
  },
  actIcon: {
    width: '32px',
    height: '32px',
    borderRadius: '9px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    flexShrink: 0,
    marginTop: '1px',
  },
  actText: { flex: 1, minWidth: 0 },
  actTitle: {
    fontSize: '12.5px',
    color: 'var(--ba-text)',
    fontWeight: 500,
    marginBottom: '2px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  actTime: {
    fontSize: '10px',
    color: 'var(--ba-text3)',
  },
}));